<%
' generated by any<code> '
Class Member

	Private prop_name

	Private prop_views

	Public Property Get name
		name = prop_name
	End Property
	Public Property Let name(var)
		prop_name = var
	End Property

	Public Property Get views
		views = prop_views
	End Property
	Public Property Let views(var)
		prop_views = var
	End Property

	Private Sub Class_Initialize
	End Sub
	Private Sub Class_Terminate
	End Sub

	PUBLIC Function getID()
		getID = 
	End Function

	PUBLIC Function checkASDF(param0, param1, param2)
		checkASDF = 
	End Function

	PRIVATE Sub setSomething(param3)
	End Sub

End Class
%>