<!--#include virtual="cls_SuperClass.asp"-->
<%
' generated by any<code> '
Class SubClass2

	Private cls_SuperClass

	Private prop_corners

	Public Property Get name
		name = cls_SuperClass.name
	End Property
	Public Property Set name(var)
		cls_SuperClass.name = var
	End Property

	Public Property Get corners
		corners = prop_corners
	End Property
	Public Property Let corners(var)
		prop_corners = var
	End Property

	Private Sub Class_Initialize
		Set cls_SuperClass = New SuperClass
	End Sub
	Private Sub Class_Terminate
		Set cls_SuperClass = nothing
	End Sub

	PUBLIC Sub run2()
	End Sub

End Class
%>