<%
' generated by any<code> '
Class SuperClass

	Private prop_name

	Public Property Get name
		name = prop_name
	End Property
	Public Property Let name(var)
		prop_name = var
	End Property

	Private Sub Class_Initialize
	End Sub
	Private Sub Class_Terminate
	End Sub

	PUBLIC Sub run()
	End Sub

End Class
%>